# Configuración del servidor
server.port=8080

# Configuración de base de datos MySQL (conectando a tu BD existente)
spring.datasource.url=jdbc:mysql://localhost:3306/Sistematricula?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de inicialización de base de datos (desactivada para usar BD existente)
spring.sql.init.mode=never

# Configuración JPA/Hibernate para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT (para futuras implementaciones)
jwt.secret=tu_clave_secreta_muy_segura_aqui_cambiar_en_produccion
jwt.expiration=86400000

# Keycloak / OAuth2 Resource Server
keycloak.auth-server-url=http://localhost:8180
keycloak.realm=Matricula
keycloak.resource=app-matricula
keycloak.credentials.secret=L4itKVl3Wpw029O6BEnWTRnkHgghqaWK

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/Matricula/protocol/openid-connect/certs

# Carpeta de archivos PDF (fuera de Backend y Frontend, no se borra con mvn clean)
recursos.static.dir=C:/Users/USUARIO/Desktop/unamba/ciclo 0 2/ds20/PROYECTO_FINAL/storage
